testing the chatbot in frontend

diff --git a/.github/workflows/ci_pipeline.yml b/.github/workflows/ci_pipeline.yml
--- a/.github/workflows/ci_pipeline.yml
+++ b/.github/workflows/ci_pipeline.yml
@@ -7,9 +7,8 @@ name: "SAST and CI Pipeline for Portfolio"
 on:
   push:
     branches:
-      # - Prod
-      # - development
-      - feature/*
+      - Prod
+      - development
   workflow_dispatch: null # manual trigger
 
 # Global permissions for the workflow
@@ -197,14 +196,14 @@ jobs:
           # ${{ github.ref_name }}
           # ${{ github.ref_name }}-${{ github.sha }}
           tags: |
-            ${{ secrets.DOCKER_HUB_USERNAME }}/personal_portfolio_3d:feature 
-            ${{ secrets.DOCKER_HUB_USERNAME }}/personal_portfolio_3d:feature-${{ github.sha }}
+            ${{ secrets.DOCKER_HUB_USERNAME }}/personal_portfolio_3d:${{ github.ref_name }} 
+            ${{ secrets.DOCKER_HUB_USERNAME }}/personal_portfolio_3d:${{ github.ref_name }}-${{ github.sha }}
 
       # Scan the Docker image for vulnerabilities before pushing
       - name: Run Trivy vulnerability scanner
         uses: aquasecurity/trivy-action@master
         with:
-          image-ref: ${{ secrets.DOCKER_HUB_USERNAME }}/personal_portfolio_3d:feature
+          image-ref: ${{ secrets.DOCKER_HUB_USERNAME }}/personal_portfolio_3d:${{ github.ref_name }}
           format: sarif
           output: trivy-results.sarif
           severity: "CRITICAL" # HIGH,MEDIUM,LOW
@@ -236,74 +235,74 @@ jobs:
           file: Dockerfile
           push: true
           tags: |
-            ${{ secrets.DOCKER_HUB_USERNAME }}/personal_portfolio_3d:feature
-            ${{ secrets.DOCKER_HUB_USERNAME }}/personal_portfolio_3d:feature-${{ github.sha }}
+            ${{ secrets.DOCKER_HUB_USERNAME }}/personal_portfolio_3d:${{ github.ref_name }}
+            ${{ secrets.DOCKER_HUB_USERNAME }}/personal_portfolio_3d:${{ github.ref_name }}-${{ github.sha }}
 
   # Build Backend Docker image
-  build_backend_docker_image_and_scan_for_vulnerabilities:
-    name: Docker Image build and Vulnerability Scanning and Push (Backend)
-    runs-on: ubuntu-latest
-    needs: static_code_analysis
-    permissions:
-      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
+  # build_backend_docker_image_and_scan_for_vulnerabilities:
+  #   name: Docker Image build and Vulnerability Scanning and Push (Backend)
+  #   runs-on: ubuntu-latest
+  #   needs: static_code_analysis
+  #   permissions:
+  #     security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
 
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
+  #     - name: Set up Docker Buildx
+  #       uses: docker/setup-buildx-action@v3
 
-      - name: Build Backend Docker image
-        uses: docker/build-push-action@v4
-        with:
-          context: .
-          file: backend/Dockerfile
-          push: false
-          load: true
-          # ${{ github.ref_name }}
-          tags: |
-            ${{ secrets.DOCKER_HUB_USERNAME }}/portfolio_backend:feature
-            ${{ secrets.DOCKER_HUB_USERNAME }}/portfolio_backend:feature-${{ github.sha }}
+  #     - name: Build Backend Docker image
+  #       uses: docker/build-push-action@v4
+  #       with:
+  #         context: .
+  #         file: backend/Dockerfile
+  #         push: false
+  #         load: true
+  #         # ${{ github.ref_name }}
+  #         tags: |
+  #           ${{ secrets.DOCKER_HUB_USERNAME }}/portfolio_backend:${{ github.ref_name }}
+  #           ${{ secrets.DOCKER_HUB_USERNAME }}/portfolio_backend:${{ github.ref_name }}-${{ github.sha }}
 
-      # Scan the Docker image for vulnerabilities before pushing
-      - name: Run Trivy vulnerability scanner on Backend
-        uses: aquasecurity/trivy-action@master
-        with:
-          image-ref: ${{ secrets.DOCKER_HUB_USERNAME }}/portfolio_backend:feature-${{ github.sha }}
-          format: sarif
-          output: trivy-backend-results.sarif
-          severity: "CRITICAL"
-          exit-code: "0"
-          ignore-unfixed: true
+  #     # Scan the Docker image for vulnerabilities before pushing
+  #     - name: Run Trivy vulnerability scanner on Backend
+  #       uses: aquasecurity/trivy-action@master
+  #       with:
+  #         image-ref: ${{ secrets.DOCKER_HUB_USERNAME }}/portfolio_backend:${{ github.ref_name }}-${{ github.sha }}
+  #         format: sarif
+  #         output: trivy-backend-results.sarif
+  #         severity: "CRITICAL"
+  #         exit-code: "0"
+  #         ignore-unfixed: true
 
-      # - name: View SARIF contents
-      #   run: cat trivy-backend-results.sarif
+  #     # - name: View SARIF contents
+  #     #   run: cat trivy-backend-results.sarif
 
-      # Upload the Trivy scan results
-      - name: Upload Trivy scan results to GitHub Security tab
-        uses: github/codeql-action/upload-sarif@v4
-        with:
-          sarif_file: "trivy-backend-results.sarif"
+  #     # Upload the Trivy scan results
+  #     - name: Upload Trivy scan results to GitHub Security tab
+  #       uses: github/codeql-action/upload-sarif@v4
+  #       with:
+  #         sarif_file: "trivy-backend-results.sarif"
 
-      # Log in to Docker Hub
-      - name: Log in to Docker Hub
-        uses: docker/login-action@v2
-        with:
-          registry: docker.io
-          username: ${{ secrets.DOCKER_HUB_USERNAME }}
-          password: ${{ secrets.DOCKER_HUB_TOKEN }}
+  #     # Log in to Docker Hub
+  #     - name: Log in to Docker Hub
+  #       uses: docker/login-action@v2
+  #       with:
+  #         registry: docker.io
+  #         username: ${{ secrets.DOCKER_HUB_USERNAME }}
+  #         password: ${{ secrets.DOCKER_HUB_TOKEN }}
 
-      # Push Backend Docker image to Docker Hub
-      - name: Push Backend Docker image
-        uses: docker/build-push-action@v4
-        with:
-          context: .
-          file: backend/Dockerfile
-          push: true
-          tags: |
-            ${{ secrets.DOCKER_HUB_USERNAME }}/portfolio_backend:feature
-            ${{ secrets.DOCKER_HUB_USERNAME }}/portfolio_backend:feature-${{ github.sha }}
+  #     # Push Backend Docker image to Docker Hub
+  #     - name: Push Backend Docker image
+  #       uses: docker/build-push-action@v4
+  #       with:
+  #         context: .
+  #         file: backend/Dockerfile
+  #         push: true
+  #         tags: |
+  #           ${{ secrets.DOCKER_HUB_USERNAME }}/portfolio_backend:${{ github.ref_name }}
+  #           ${{ secrets.DOCKER_HUB_USERNAME }}/portfolio_backend:${{ github.ref_name }}-${{ github.sha }}
 
   # Check if both Frontend and Backend Docker images are built and push Docker images to Docker Hub
   build_and_push_docker_images:
@@ -312,8 +311,7 @@ jobs:
     needs:
       [
         build_frontend_docker_image_and_scan_for_vulnerabilities,
-        build_backend_docker_image_and_scan_for_vulnerabilities,
-      ]
+      ] # build_backend_docker_image_and_scan_for_vulnerabilities,
     permissions:
       packages: write
 
@@ -328,14 +326,14 @@ jobs:
 
       # Verify both Docker images were pushed successfully
       - name: Verify Docker images push
+          # echo "Verifying Backend image..."
+          # docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/portfolio_backend:${{ github.ref_name }} || \
+          # docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/portfolio_backend:${{ github.ref_name }}-${{ github.sha }}
         run: |
           echo "Verifying Frontend image..."
-          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/personal_portfolio_3d:feature || \
-          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/personal_portfolio_3d:feature-${{ github.sha }}
+          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/personal_portfolio_3d:${{ github.ref_name }} || \
+          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/personal_portfolio_3d:${{ github.ref_name }}-${{ github.sha }}
 
-          echo "Verifying Backend image..."
-          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/portfolio_backend:feature || \
-          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/portfolio_backend:feature-${{ github.sha }}
 
           if [ $? -ne 0 ]; then
             echo "Docker image push failed."
@@ -344,49 +342,49 @@ jobs:
             echo "All Docker images pushed successfully."
           fi
 
-  # Update the Docker image tags in the GitOps repository
-  # update_docker_image_tags_in_gitops_repo:
-  #   name: Update Docker Image Tags in GitOps Repository
-  #   runs-on: ubuntu-latest
-  #   needs: build_and_push_docker_images
-  #   permissions:
-  #     contents: write
-  #     id-token: write
+  Update the Docker image tags in the GitOps repository
+  update_docker_image_tags_in_gitops_repo:
+    name: Update Docker Image Tags in GitOps Repository
+    runs-on: ubuntu-latest
+    needs: build_and_push_docker_images
+    permissions:
+      contents: write
+      id-token: write
 
-  #   steps:
-  #     # Update the Docker image tags in the GitOps repository
-  #     - name: Checkout GitOps repository
-  #       uses: actions/checkout@v4
-  #       with:
-  #         repository: Pavan-Kumar-Adapala/gitops-portfolio-3d-k8s
-  #         ref: feature
-  #         token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
+    steps:
+      # Update the Docker image tags in the GitOps repository
+      - name: Checkout GitOps repository
+        uses: actions/checkout@v4
+        with:
+          repository: Pavan-Kumar-Adapala/gitops-portfolio-3d-k8s
+          ref: ${{ github.ref_name }}
+          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
 
-  #     - name: Update Docker image tags in deployment.yaml
-  #       run: |
-  #         # Update Frontend image
-  #         sed -i "s|\(image:\s*\)adapaladocker/personal_portfolio_3d:[^[:space:]]*|\1adapaladocker/personal_portfolio_3d:feature-${{ github.sha }}|" k8s/deployment.yaml
+      - name: Update Docker image tags in deployment.yaml
+        run: |
+          # Update Frontend image
+          sed -i "s|\(image:\s*\)adapaladocker/personal_portfolio_3d:[^[:space:]]*|\1adapaladocker/personal_portfolio_3d:${{ github.ref_name }}-${{ github.sha }}|" k8s/deployment.yaml
 
-  #         # Update Backend image
-  #         sed -i "s|\(image:\s*\)adapaladocker/portfolio_backend:[^[:space:]]*|\1adapaladocker/portfolio_backend:feature-${{ github.sha }}|" k8s/deployment.yaml
+          # Update Backend image
+          sed -i "s|\(image:\s*\)adapaladocker/portfolio_backend:[^[:space:]]*|\1adapaladocker/portfolio_backend:${{ github.ref_name }}-${{ github.sha }}|" k8s/deployment.yaml
 
-  #     # Commit and push changes
-  #     - name: Commit and push changes
-  #       run: |
-  #         git config --global user.name "GitHub Actions"
-  #         git config --global user.email "github-actions[bot]@users.noreply.github.com"
-  #         git add k8s/deployment.yaml
-  #         git commit -m "Update Docker image tag & NODE_ENV for branch ${{ github.ref_name }}"
-  #         git push origin ${{ github.ref_name }}
+      # Commit and push changes
+      - name: Commit and push changes
+        run: |
+          git config --global user.name "GitHub Actions"
+          git config --global user.email "github-actions[bot]@users.noreply.github.com"
+          git add k8s/deployment.yaml
+          git commit -m "Update Docker image tag & NODE_ENV for branch ${{ github.ref_name }}"
+          git push origin ${{ github.ref_name }}
 
-  #     - name: Check if the push was successful
-  #       run: |
-  #         if [ $? -ne 0 ]; then
-  #           echo "Failed to push changes to GitOps repository."
-  #           exit 1
-  #         else
-  #           echo "Changes pushed successfully to GitOps repository."
-  #         fi
+      - name: Check if the push was successful
+        run: |
+          if [ $? -ne 0 ]; then
+            echo "Failed to push changes to GitOps repository."
+            exit 1
+          else
+            echo "Changes pushed successfully to GitOps repository."
+          fi
 
   # ---
 
