ci_pipeline docker image tag changed to feature

diff --git a/.github/workflows/ci_pipeline.yml b/.github/workflows/ci_pipeline.yml
--- a/.github/workflows/ci_pipeline.yml
+++ b/.github/workflows/ci_pipeline.yml
@@ -202,8 +202,9 @@ jobs:
       # Scan the Docker image for vulnerabilities before pushing
       - name: Run Trivy vulnerability scanner
         uses: aquasecurity/trivy-action@0.28.0
+        # ${{ github.ref_name }}
         with:
-          image-ref: adapaladocker/personal_portfolio_3d:${{ github.ref_name }}
+          image-ref: adapaladocker/personal_portfolio_3d:feature
           format: sarif
           output: trivy-results.sarif
           severity: "CRITICAL" # HIGH,MEDIUM,LOW
@@ -247,9 +248,10 @@ jobs:
           context: .
           file: backend/Dockerfile
           push: false
+          # ${{ github.ref_name }}
           tags: |
-            ${{ secrets.DOCKER_HUB_USERNAME }}/portfolio_backend:${{ github.ref_name }}
-            ${{ secrets.DOCKER_HUB_USERNAME }}/portfolio_backend:${{ github.ref_name }}-${{ github.sha }}
+            ${{ secrets.DOCKER_HUB_USERNAME }}/portfolio_backend:feature
+            ${{ secrets.DOCKER_HUB_USERNAME }}/portfolio_backend:feature-${{ github.sha }}
 
   # Scan Backend Docker image for vulnerabilities
   scan_backend_docker_image:
@@ -272,12 +274,12 @@ jobs:
           context: .
           file: backend/Dockerfile
           push: false
-          tags: adapaladocker/portfolio_backend:${{ github.ref_name }}
+          tags: adapaladocker/portfolio_backend:feature-${{ github.sha }}
 
       - name: Run Trivy vulnerability scanner on Backend
         uses: aquasecurity/trivy-action@0.28.0
         with:
-          image-ref: adapaladocker/portfolio_backend:${{ github.ref_name }}
+          image-ref: adapaladocker/portfolio_backend:feature-${{ github.sha }}
           format: sarif
           output: trivy-backend-results.sarif
           severity: "CRITICAL"
@@ -322,8 +324,8 @@ jobs:
           file: Dockerfile
           push: true
           tags: |
-            ${{ secrets.DOCKER_HUB_USERNAME }}/personal_portfolio_3d:${{ github.ref_name }}
-            ${{ secrets.DOCKER_HUB_USERNAME }}/personal_portfolio_3d:${{ github.ref_name }}-${{ github.sha }}
+            ${{ secrets.DOCKER_HUB_USERNAME }}/personal_portfolio_3d:feature
+            ${{ secrets.DOCKER_HUB_USERNAME }}/personal_portfolio_3d:feature-${{ github.sha }}
 
       # Push Backend Docker image to Docker Hub
       - name: Push Backend Docker image
@@ -333,19 +335,19 @@ jobs:
           file: backend/Dockerfile
           push: true
           tags: |
-            ${{ secrets.DOCKER_HUB_USERNAME }}/portfolio_backend:${{ github.ref_name }}
-            ${{ secrets.DOCKER_HUB_USERNAME }}/portfolio_backend:${{ github.ref_name }}-${{ github.sha }}
+            ${{ secrets.DOCKER_HUB_USERNAME }}/portfolio_backend:feature
+            ${{ secrets.DOCKER_HUB_USERNAME }}/portfolio_backend:feature-${{ github.sha }}
 
       # Verify both Docker images were pushed successfully
       - name: Verify Docker images push
         run: |
           echo "Verifying Frontend image..."
-          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/personal_portfolio_3d:${{ github.ref_name }} || \
-          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/personal_portfolio_3d:${{ github.ref_name }}-${{ github.sha }}
+          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/personal_portfolio_3d:feature || \
+          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/personal_portfolio_3d:feature-${{ github.sha }}
 
           echo "Verifying Backend image..."
-          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/portfolio_backend:${{ github.ref_name }} || \
-          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/portfolio_backend:${{ github.ref_name }}-${{ github.sha }}
+          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/portfolio_backend:feature || \
+          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/portfolio_backend:feature-${{ github.sha }}
 
           if [ $? -ne 0 ]; then
             echo "Docker image push failed."
@@ -355,48 +357,50 @@ jobs:
           fi
 
   # Update the Docker image tags in the GitOps repository
-  update_docker_image_tags_in_gitops_repo:
-    name: Update Docker Image Tags in GitOps Repository
-    runs-on: ubuntu-latest
-    needs: build_and_push_docker_images
-    permissions:
-      contents: write
-      id-token: write
+  # update_docker_image_tags_in_gitops_repo:
+  #   name: Update Docker Image Tags in GitOps Repository
+  #   runs-on: ubuntu-latest
+  #   needs: build_and_push_docker_images
+  #   permissions:
+  #     contents: write
+  #     id-token: write
 
-    steps:
-      # Update the Docker image tags in the GitOps repository
-      - name: Checkout GitOps repository
-        uses: actions/checkout@v4
-        with:
-          repository: Pavan-Kumar-Adapala/gitops-portfolio-3d-k8s
-          ref: ${{ github.ref_name }}
-          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
+  #   steps:
+  #     # Update the Docker image tags in the GitOps repository
+  #     - name: Checkout GitOps repository
+  #       uses: actions/checkout@v4
+  #       with:
+  #         repository: Pavan-Kumar-Adapala/gitops-portfolio-3d-k8s
+  #         ref: feature
+  #         token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
 
-      - name: Update Docker image tags in deployment.yaml
-        run: |
-          # Update Frontend image
-          sed -i "s|\(image:\s*\)adapaladocker/personal_portfolio_3d:[^[:space:]]*|\1adapaladocker/personal_portfolio_3d:${{ github.ref_name }}-${{ github.sha }}|" k8s/deployment.yaml
+  #     - name: Update Docker image tags in deployment.yaml
+  #       run: |
+  #         # Update Frontend image
+  #         sed -i "s|\(image:\s*\)adapaladocker/personal_portfolio_3d:[^[:space:]]*|\1adapaladocker/personal_portfolio_3d:feature-${{ github.sha }}|" k8s/deployment.yaml
 
-          # Update Backend image
-          sed -i "s|\(image:\s*\)adapaladocker/portfolio_backend:[^[:space:]]*|\1adapaladocker/portfolio_backend:${{ github.ref_name }}-${{ github.sha }}|" k8s/deployment.yaml
+  #         # Update Backend image
+  #         sed -i "s|\(image:\s*\)adapaladocker/portfolio_backend:[^[:space:]]*|\1adapaladocker/portfolio_backend:feature-${{ github.sha }}|" k8s/deployment.yaml
 
-      # Commit and push changes
-      - name: Commit and push changes
-        run: |
-          git config --global user.name "GitHub Actions"
-          git config --global user.email "github-actions[bot]@users.noreply.github.com"
-          git add k8s/deployment.yaml
-          git commit -m "Update Docker image tag & NODE_ENV for branch ${{ github.ref_name }}"
-          git push origin ${{ github.ref_name }}
+  #     # Commit and push changes
+  #     - name: Commit and push changes
+  #       run: |
+  #         git config --global user.name "GitHub Actions"
+  #         git config --global user.email "github-actions[bot]@users.noreply.github.com"
+  #         git add k8s/deployment.yaml
+  #         git commit -m "Update Docker image tag & NODE_ENV for branch ${{ github.ref_name }}"
+  #         git push origin ${{ github.ref_name }}
 
-      - name: Check if the push was successful
-        run: |
-          if [ $? -ne 0 ]; then
-            echo "Failed to push changes to GitOps repository."
-            exit 1
-          else
-            echo "Changes pushed successfully to GitOps repository."
-          fi
+  #     - name: Check if the push was successful
+  #       run: |
+  #         if [ $? -ne 0 ]; then
+  #           echo "Failed to push changes to GitOps repository."
+  #           exit 1
+  #         else
+  #           echo "Changes pushed successfully to GitOps repository."
+  #         fi
+
+  # ---
 
   # Another job to deploy the application to github pages using gh-pages and custom domain
   # deploy_to_github_pages:
